export const ABOUT_LIST_REQUEST = 'ABOUT_LIST_REQUEST';
export const ABOUT_LIST_SUCCESS = 'ABOUT_LIST_SUCCESS';
export const ABOUT_LIST_FAIL = 'ABOUT_LIST_FAIL';

export const ABOUT_ADD_REQUEST = 'ABOUT_ADD_REQUEST';
export const ABOUT_ADD_SUCCESS = 'ABOUT_ADD_SUCCESS';
export const ABOUT_ADD_FAIL = 'ABOUT_ADD_FAIL';

export const ABOUT_UPDATE_REQUEST = 'ABOUT_UPDATE_REQUEST';
export const ABOUT_UPDATE_SUCCESS = 'ABOUT_UPDATE_SUCCESS';
export const ABOUT_UPDATE_FAIL = 'ABOUT_UPDATE_FAIL';

export const ABOUT_DELETE_REQUEST = 'ABOUT_DELETE_REQUEST';
export const ABOUT_DELETE_SUCCESS = 'ABOUT_DELETE_SUCCESS';
export const ABOUT_DELETE_FAIL = 'ABOUT_DELETE_FAIL';


export const PRIVACYPOLICY_LIST_REQUEST = 'PRIVACYPOLICY_LIST_REQUEST';
export const PRIVACYPOLICY_LIST_SUCCESS = 'PRIVACYPOLICY_LIST_SUCCESS';
export const PRIVACYPOLICY_LIST_FAIL = 'PRIVACYPOLICY_LIST_FAIL';

export const PRIVACYPOLICY_ADD_REQUEST = 'PRIVACYPOLICY_ADD_REQUEST';
export const PRIVACYPOLICY_ADD_SUCCESS = 'PRIVACYPOLICY_ADD_SUCCESS';
export const PRIVACYPOLICY_ADD_FAIL = 'PRIVACYPOLICY_ADD_FAIL';

export const PRIVACYPOLICY_UPDATE_REQUEST = 'PRIVACYPOLICY_UPDATE_REQUEST';
export const PRIVACYPOLICY_UPDATE_SUCCESS = 'PRIVACYPOLICY_UPDATE_SUCCESS';
export const PRIVACYPOLICY_UPDATE_FAIL = 'PRIVACYPOLICY_UPDATE_FAIL';

export const PRIVACYPOLICY_DELETE_REQUEST = 'PRIVACYPOLICY_DELETE_REQUEST';
export const PRIVACYPOLICY_DELETE_SUCCESS = 'PRIVACYPOLICY_DELETE_SUCCESS';
export const PRIVACYPOLICY_DELETE_FAIL = 'PRIVACYPOLICY_DELETE_FAIL';


export const EMAILLIST_LIST_REQUEST = 'EMAILLIST_LIST_REQUEST';
export const EMAILLIST_LIST_SUCCESS = 'EMAILLIST_LIST_SUCCESS';
export const EMAILLIST_LIST_FAIL = 'EMAILLIST_LIST_FAIL';

export const EMAILLIST_DELETE_REQUEST = 'EMAILLIST_DELETE_REQUEST';
export const EMAILLIST_DELETE_SUCCESS = 'EMAILLIST_DELETE_SUCCESS';
export const EMAILLIST_DELETE_FAIL = 'EMAILLIST_DELETE_FAIL';



export const SOCIALACCOUNT_LIST_REQUEST = 'SOCIALACCOUNT_LIST_REQUEST';
export const SOCIALACCOUNT_LIST_SUCCESS = 'SOCIALACCOUNT_LIST_SUCCESS';
export const SOCIALACCOUNT_LIST_FAIL = 'SOCIALACCOUNT_LIST_FAIL';

export const SOCIALACCOUNT_ADD_REQUEST = 'SOCIALACCOUNT_ADD_REQUEST';
export const SOCIALACCOUNT_ADD_SUCCESS = 'SOCIALACCOUNT_ADD_SUCCESS';
export const SOCIALACCOUNT_ADD_FAIL = 'SOCIALACCOUNT_ADD_FAIL';

export const SOCIALACCOUNT_UPDATE_REQUEST = 'SOCIALACCOUNT_UPDATE_REQUEST';
export const SOCIALACCOUNT_UPDATE_SUCCESS = 'SOCIALACCOUNT_UPDATE_SUCCESS';
export const SOCIALACCOUNT_UPDATE_FAIL = 'SOCIALACCOUNT_UPDATE_FAIL';

export const SOCIALACCOUNT_DELETE_REQUEST = 'SOCIALACCOUNT_DELETE_REQUEST';
export const SOCIALACCOUNT_DELETE_SUCCESS = 'SOCIALACCOUNT_DELETE_SUCCESS';
export const SOCIALACCOUNT_DELETE_FAIL = 'SOCIALACCOUNT_DELETE_FAIL';


export const CURRENCY_LIST_REQUEST = 'CURRENCY_LIST_REQUEST';
export const CURRENCY_LIST_SUCCESS = 'CURRENCY_LIST_SUCCESS';
export const CURRENCY_LIST_FAIL = 'CURRENCY_LIST_FAIL';

export const CURRENCY_ADD_REQUEST = 'CURRENCY_ADD_REQUEST';
export const CURRENCY_ADD_SUCCESS = 'CURRENCY_ADD_SUCCESS';
export const CURRENCY_ADD_FAIL = 'CURRENCY_ADD_FAIL';

export const CURRENCY_UPDATE_REQUEST = 'CURRENCY_UPDATE_REQUEST';
export const CURRENCY_UPDATE_SUCCESS = 'CURRENCY_UPDATE_SUCCESS';
export const CURRENCY_UPDATE_FAIL = 'CURRENCY_UPDATE_FAIL';

export const CURRENCY_DELETE_REQUEST = 'CURRENCY_DELETE_REQUEST';
export const CURRENCY_DELETE_SUCCESS = 'CURRENCY_DELETE_SUCCESS';
export const CURRENCY_DELETE_FAIL = 'CURRENCY_DELETE_FAIL';


export const COUNTRY_LIST_REQUEST = 'COUNTRY_LIST_REQUEST';
export const COUNTRY_LIST_SUCCESS = 'COUNTRY_LIST_SUCCESS';
export const COUNTRY_LIST_FAIL = 'COUNTRY_LIST_FAIL';

export const COUNTRY_ADD_REQUEST = 'COUNTRY_ADD_REQUEST';
export const COUNTRY_ADD_SUCCESS = 'COUNTRY_ADD_SUCCESS';
export const COUNTRY_ADD_FAIL = 'COUNTRY_ADD_FAIL';

export const COUNTRY_UPDATE_REQUEST = 'COUNTRY_UPDATE_REQUEST';
export const COUNTRY_UPDATE_SUCCESS = 'COUNTRY_UPDATE_SUCCESS';
export const COUNTRY_UPDATE_FAIL = 'COUNTRY_UPDATE_FAIL';

export const COUNTRY_DELETE_REQUEST = 'COUNTRY_DELETE_REQUEST';
export const COUNTRY_DELETE_SUCCESS = 'COUNTRY_DELETE_SUCCESS';
export const COUNTRY_DELETE_FAIL = 'COUNTRY_DELETE_FAIL';