export const ABOUT_LIST_REQUEST = 'ABOUT_LIST_REQUEST';
export const ABOUT_LIST_SUCCESS = 'ABOUT_LIST_SUCCESS';
export const ABOUT_LIST_FAIL = 'ABOUT_LIST_FAIL';

export const ABOUT_ADD_REQUEST = 'ABOUT_ADD_REQUEST';
export const ABOUT_ADD_SUCCESS = 'ABOUT_ADD_SUCCESS';
export const ABOUT_ADD_FAIL = 'ABOUT_ADD_FAIL';

export const ABOUT_UPDATE_REQUEST = 'ABOUT_UPDATE_REQUEST';
export const ABOUT_UPDATE_SUCCESS = 'ABOUT_UPDATE_SUCCESS';
export const ABOUT_UPDATE_FAIL = 'ABOUT_UPDATE_FAIL';

export const ABOUT_DELETE_REQUEST = 'ABOUT_DELETE_REQUEST';
export const ABOUT_DELETE_SUCCESS = 'ABOUT_DELETE_SUCCESS';
export const ABOUT_DELETE_FAIL = 'ABOUT_DELETE_FAIL';


export const PRIVACYPOLICY_LIST_REQUEST = 'PRIVACYPOLICY_LIST_REQUEST';
export const PRIVACYPOLICY_LIST_SUCCESS = 'PRIVACYPOLICY_LIST_SUCCESS';
export const PRIVACYPOLICY_LIST_FAIL = 'PRIVACYPOLICY_LIST_FAIL';

export const PRIVACYPOLICY_ADD_REQUEST = 'PRIVACYPOLICY_ADD_REQUEST';
export const PRIVACYPOLICY_ADD_SUCCESS = 'PRIVACYPOLICY_ADD_SUCCESS';
export const PRIVACYPOLICY_ADD_FAIL = 'PRIVACYPOLICY_ADD_FAIL';

export const PRIVACYPOLICY_UPDATE_REQUEST = 'PRIVACYPOLICY_UPDATE_REQUEST';
export const PRIVACYPOLICY_UPDATE_SUCCESS = 'PRIVACYPOLICY_UPDATE_SUCCESS';
export const PRIVACYPOLICY_UPDATE_FAIL = 'PRIVACYPOLICY_UPDATE_FAIL';

export const PRIVACYPOLICY_DELETE_REQUEST = 'PRIVACYPOLICY_DELETE_REQUEST';
export const PRIVACYPOLICY_DELETE_SUCCESS = 'PRIVACYPOLICY_DELETE_SUCCESS';
export const PRIVACYPOLICY_DELETE_FAIL = 'PRIVACYPOLICY_DELETE_FAIL';


export const EMAILLIST_LIST_REQUEST = 'EMAILLIST_LIST_REQUEST';
export const EMAILLIST_LIST_SUCCESS = 'EMAILLIST_LIST_SUCCESS';
export const EMAILLIST_LIST_FAIL = 'EMAILLIST_LIST_FAIL';

export const EMAILLIST_DELETE_REQUEST = 'EMAILLIST_DELETE_REQUEST';
export const EMAILLIST_DELETE_SUCCESS = 'EMAILLIST_DELETE_SUCCESS';
export const EMAILLIST_DELETE_FAIL = 'EMAILLIST_DELETE_FAIL';